apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: jq-simple
spec:
  vertices:
    - name: in
      source:
        generator:
          rpu: 1
          duration: 1s

    - name: leoflow-map-jq
      udf:
        container:
          imagePullPolicy: Never
          image: leoflow
          command: [ '/leoflow' ]
          args: [ 'map', 'jq' ]
          env:
            - name: JQ_EXPRESSION
              value: |
                { 
                  "ext_id": (.Data.value | tostring),
                  "new_field": "This is a new field"
                }
    - name: out
      sink:
        log: {}
  edges:
    - from: in
      to: leoflow-map-jq
    - from: leoflow-map-jq
      to: out
